In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('CVD_cleaned.csv')

In [11]:
#Author : ALPHIREE from Kaggle.com 
#(More about this Dataset: https://www.kaggle.com/datasets/alphiree/cardiovascular-diseases-risk-prediction-dataset)

In [8]:
df.head()

,General_Health,Checkup,Exercise,Heart_Disease,Skin_Cancer,Other_Cancer,Depression,Diabetes,Arthritis,Sex,Age_Category,Height_(cm),Weight_(kg),BMI,Smoking_History,Alcohol_Consumption,Fruit_Consumption,Green_Vegetables_Consumption,FriedPotato_Consumption
0,Poor,Within the past 2 years,No,No,No,No,No,No,Yes,Female,70-74,150.0,32.66,14.54,Yes,0.0,30.0,16.0,12.0
1,Very Good,Within the past year,No,Yes,No,No,No,Yes,No,Female,70-74,165.0,77.11,28.29,No,0.0,30.0,0.0,4.0
2,Very Good,Within the past year,Yes,No,No,No,No,Yes,No,Female,60-64,163.0,88.45,33.47,No,4.0,12.0,3.0,16.0
3,Poor,Within the past year,Yes,Yes,No,No,No,Yes,No,Male,75-79,180.0,93.44,28.73,No,0.0,30.0,30.0,8.0
4,Good,Within the past year,No,No,No,No,No,No,No,Male,80+,191.0,88.45,24.37,Yes,0.0,8.0,4.0,0.0

In [17]:
df.Checkup.unique()

array(['Within the past 2 years', 'Within the past year',
       '5 or more years ago', 'Within the past 5 years', 'Never'],
      dtype=object)

In [18]:
df['Checkup']=df['Checkup'].replace({'Within the past 2 years':'<=2 years',
                                     'Within the past year':'<=1 year',
                                    '5 or more years ago':'>=5 years',
                                    'Within the past 5 years':'<=5 years'})

In [ ]:
#converting Alcohol_consumption, Fruit_consumption, Green_Vegetables_Consumption and FriedPotato_Consumption into 'yes/no'

In [37]:
def convert_to_yes_no(value):
    return 'Yes' if value != 0 else 'No'

df['Alcohol_Consumption']=df['Alcohol_Consumption'].apply(convert_to_yes_no)
df['Fruit_Consumption']=df['Fruit_Consumption'].apply(convert_to_yes_no)
df['Green_Vegetables_Consumption']=df['Green_Vegetables_Consumption'].apply(convert_to_yes_no)
df['FriedPotato_Consumption']=df['FriedPotato_Consumption'].apply(convert_to_yes_no)

,General_Health,Checkup,Exercise,Heart_Disease,Skin_Cancer,Other_Cancer,Depression,Diabetes,Arthritis,Sex,Age_Category,Height_(cm),Weight_(kg),BMI,Smoking_History,Alcohol_Consumption,Fruit_Consumption,Green_Vegetables_Consumption,FriedPotato_Consumption
Patient,,,,,,,,,,,,,,,,,,,
2,Poor,<=2 years,No,No,No,No,No,No,Yes,Female,70-74,150.0,32.66,14.54,Yes,No,Yes,Yes,Yes
3,Very Good,<=1 year,No,Yes,No,No,No,Yes,No,Female,70-74,165.0,77.11,28.29,No,No,Yes,No,Yes
4,Very Good,<=1 year,Yes,No,No,No,No,Yes,No,Female,60-64,163.0,88.45,33.47,No,Yes,Yes,Yes,Yes

In [ ]:
#MNaming the index 'Patients' as there are no other patient identification columns

In [45]:
df.index = df.index +1
df = df.rename_axis("Patient")
df.head(3)

,General_Health,Checkup,Exercise,Heart_Disease,Skin_Cancer,Other_Cancer,Depression,Diabetes,Arthritis,Sex,Age_Category,Height_(cm),Weight_(kg),BMI,Smoking_History,Alcohol_Consumption,Fruit_Consumption,Green_Vegetables_Consumption,FriedPotato_Consumption
Patient,,,,,,,,,,,,,,,,,,,
1,Poor,<=2 years,No,No,No,No,No,No,Yes,Female,70-74,150.0,32.66,14.54,Yes,No,Yes,Yes,Yes
2,Very Good,<=1 year,No,Yes,No,No,No,Yes,No,Female,70-74,165.0,77.11,28.29,No,No,Yes,No,Yes
3,Very Good,<=1 year,Yes,No,No,No,No,Yes,No,Female,60-64,163.0,88.45,33.47,No,Yes,Yes,Yes,Yes

In [47]:
df.isnull().sum()

General_Health                  0
Checkup                         0
Exercise                        0
Heart_Disease                   0
Skin_Cancer                     0
Other_Cancer                    0
Depression                      0
Diabetes                        0
Arthritis                       0
Sex                             0
Age_Category                    0
Height_(cm)                     0
Weight_(kg)                     0
BMI                             0
Smoking_History                 0
Alcohol_Consumption             0
Fruit_Consumption               0
Green_Vegetables_Consumption    0
FriedPotato_Consumption         0
dtype: int64

In [ ]:
# The data set is cleaned and is ready for further analysis